# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/Feng96"

[social.params]
icon = "brand-github"

[[social]]
identifier = "instagram"
name = "Instagram"
url = "https://instagram.com/yinanfeng945"

[social.params]
icon = "brand-instagram"

[[social]]
identifier = "mail"
name = "E-Mail"
url = "mailto:yfeng21@vols.utk.edu"

[social.params]
icon = "mail"